services:
  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080  # (optional) dashboard - disable for production!
    volumes:
      - /opt/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-ssl-certs:/etc/ssl-certs
    # -- (Optional) When using Google Domains as Cert Resolver
    #environment:
    #  - GOOGLE_DOMAINS_ACCESS_TOKEN=google-domains-api-token
    # -- (Optional) When using a custom network
    # networks:
    #   - your-traefik-network
    restart: unless-stopped
